/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment5;

import java.util.Scanner;

public class App {
     
    public static void main(String[] args) {
         Scanner scan = new Scanner(System.in);

         //Taking input for evenCheck
        System.out.println("Enter number to check if its even. ");
        int number = scan.nextInt();
        EvenCheck evenCheck = new EvenCheck();
        Boolean evenResult = evenCheck.checkEvenNumber(number);
        if(evenResult==null) System.out.println("Invalid Number");
        else if (evenResult) System.out.println(number + " is Even Number");
        else System.out.println(number + " is not Even Number");

        //Taking input for LeapYear
        System.out.println("Enter Year to check for leap year or not ");
        int year=scan.nextInt();
        LeapYear leapYear=new LeapYear();
        Boolean leapYearRes=leapYear.checkYear(year);
        if (leapYearRes==null) System.out.println("Invalid YEAR");
        else if(leapYearRes) System.out.println(year+"is a leap year");
        else System.out.println(number + " is not leap year");

        //Taking input for Median
        System.out.print("Enter the number of elements you want to store: ");
        int n=scan.nextInt();
        if(n==0) System.out.println("Invalid ArraySize");
        Float[] array = new Float[n];
        System.out.println("Enter the elements of the array: ");
        for(int i=0; i<n; i++)
        {
            array[i]=scan.nextFloat();
        }
        Median median=new Median();
        double medianRes=median.findMedian(array,n);
        System.out.println("Median is" + medianRes);

        //Taking input for Palindrome
        System.out.print("Enter the String which you have to check ");
        String str=scan.nextLine();
        Palindrome palindrome=new Palindrome();
        Boolean palindromeRes= palindrome.checkPalindrome(str);
        if (palindromeRes==Boolean.TRUE) System.out.println("This String is palindrome");
        else System.out.println("This String is not palindrome");

        //Taking input for TaxiFare
        System.out.print("Enter the distance: ");
        int dis= scan.nextInt();
        if (dis==0) System.out.println("Invalid distance");
        TaxiFare taxiFare=new TaxiFare();
        double total=taxiFare.CalculateTaxiFare(dis);
        System.out.println("Your total fare is"+total);
    }
}
